import * as THREE from 'three';
import './style.css';
import {stepVehicle} from './driving.js';
const $=s=>document.querySelector(s);
$('#app').innerHTML=`<header><div class="logo">APEX<small>小小赛车手 · KART CLUB</small></div><div class="actions"><button id="camera">切换俯视</button><button id="reset">重新开始</button></div></header><div class="banner">SUNNY CIRCUIT / 阳光环道</div><section class="timing"><div><small>完成圈数</small><strong id="laps">0</strong></div><div><small>当前圈速</small><strong id="time">00:00.00</strong></div><div><small>最佳圈速</small><strong id="best">—</strong></div></section><section class="help"><b>你的第一圈，从这里开始。</b>↑ / W 加速 · ↓ / S 刹车、倒车<br>← → / A D 转向 · 空格急刹 · R 重开</section><div class="speed"><b id="speed">0</b><span>KM / H</span></div><div class="touch"><div><button data-key="ArrowLeft" aria-label="左转">←</button><button data-key="ArrowRight" aria-label="右转">→</button></div><div><button data-key="ArrowDown" aria-label="刹车倒车">↓</button><button data-key="ArrowUp" aria-label="加速">↑</button></div></div><div class="toast" role="status"></div>`;
const scene=new THREE.Scene();scene.background=new THREE.Color('#badce7');scene.fog=new THREE.Fog('#badce7',100,240);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,matchMedia('(pointer:coarse)').matches?1.25:1.7));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;$('#app').appendChild(renderer.domElement);
const camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.1,300);scene.add(new THREE.HemisphereLight('#d7efff','#8d9563',2.6));const sun=new THREE.DirectionalLight('#fff0d0',3);sun.position.set(-25,55,25);sun.castShadow=true;sun.shadow.mapSize.set(matchMedia('(pointer:coarse)').matches?1024:2048,matchMedia('(pointer:coarse)').matches?1024:2048);Object.assign(sun.shadow.camera,{left:-65,right:65,top:65,bottom:-65,near:1,far:140});sun.shadow.normalBias=.04;scene.add(sun);
const mat=c=>new THREE.MeshStandardMaterial({color:c,roughness:.8});const asphalt=mat('#48565b'),grass=mat('#77a950'),red=mat('#ee643d'),white=mat('#f5eee0'),black=mat('#20282c'),metal=new THREE.MeshStandardMaterial({color:'#73858c',metalness:.6,roughness:.4});
function mesh(g,m,x=0,y=0,z=0,parent=scene){const o=new THREE.Mesh(g,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o;}const box=(w,h,d,m,x,y,z,p)=>mesh(new THREE.BoxGeometry(w,h,d),m,x,y,z,p);
const ground=mesh(new THREE.PlaneGeometry(500,500),grass);ground.rotation.x=-Math.PI/2;ground.castShadow=false;
const RX=36,RZ=24,WIDTH=9;function ring(rx,rz,width,material,y){const vertices=[],indices=[];for(let i=0;i<=256;i++){const a=i/256*Math.PI*2;for(const s of [-1,1])vertices.push(Math.cos(a)*(rx+s*width/2),y,Math.sin(a)*(rz+s*width/2));if(i<256){const n=i*2;indices.push(n,n+2,n+1,n+1,n+2,n+3);}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));g.setIndex(indices);g.computeVertexNormals();return mesh(g,material);}
ring(RX,RZ,WIDTH,asphalt,.035);
for(let i=0;i<144;i++){const a=i/144*Math.PI*2;for(const side of [-1,1]){const x=Math.cos(a)*(RX+side*4.6),z=Math.sin(a)*(RZ+side*4.6);const curb=box(1.0,.12,.62,i%2?white:red,x,.075,z);curb.rotation.y=-Math.atan2(Math.cos(a)*RZ,-Math.sin(a)*RX);}if(i%4===0){const dash=box(1.15,.015,.13,white,Math.cos(a)*RX,.055,Math.sin(a)*RZ);dash.rotation.y=-Math.atan2(Math.cos(a)*RZ,-Math.sin(a)*RX);}}
for(let row=0;row<2;row++)for(let col=0;col<12;col++)box(.72,.02,.7,(row+col)%2?black:white,RX-4+col*.72,.07,row*.7-.7);
// Start gantry and paddock.
for(const x of [RX-5.3,RX+5.3])box(.35,8,.35,metal,x,4,0);box(11.1,1.1,.35,black,RX,8,0);const sign=document.createElement('canvas');sign.width=1024;sign.height=128;const ctx=sign.getContext('2d');ctx.fillStyle='#23333b';ctx.fillRect(0,0,1024,128);ctx.fillStyle='#fff3dc';ctx.font='bold italic 75px sans-serif';ctx.textAlign='center';ctx.fillText('APEX   /   START',512,91);const signTex=new THREE.CanvasTexture(sign);signTex.colorSpace=THREE.SRGBColorSpace;const board=mesh(new THREE.PlaneGeometry(10.6,1),new THREE.MeshBasicMaterial({map:signTex,side:THREE.DoubleSide}),RX,8,.19);board.castShadow=false;
for(let i=0;i<4;i++){const x=-12+i*8;box(6,2.5,5,white,x,1.25,-4);const roof=mesh(new THREE.ConeGeometry(4.6,1.8,4),i%2?red:mat('#3c889c'),x,3.2,-4);roof.rotation.y=Math.PI/4;box(4,1.8,.05,mat('#3e626b'),x,1,-1.46);}
let seed=15;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}for(let i=0;i<95;i++){const a=rand()*6.28,r=1.35+rand()*.7,x=Math.cos(a)*RX*r,z=Math.sin(a)*RZ*r;const h=3+rand()*4;mesh(new THREE.CylinderGeometry(.18,.32,h,7),mat('#8d7655'),x,h/2,z);const crown=mesh(new THREE.IcosahedronGeometry(h*.55,1),mat(['#4e8752','#639654','#83a860'][i%3]),x,h,z);crown.scale.y=1.25;}
for(let i=0;i<100;i++){const a=i/100*6.28;const x=Math.cos(a)*(RX+7),z=Math.sin(a)*(RZ+7);const fence=box(1.8,.7,.4,i%4<2?white:red,x,.4,z);fence.rotation.y=-Math.atan2(Math.cos(a)*RZ,-Math.sin(a)*RX);}
const kart=new THREE.Group();scene.add(kart);box(1.15,.22,1.9,red,0,.42,0,kart);box(1.35,.18,.5,red,0,.33,.95,kart);box(1.4,.15,.18,metal,0,.26,1.25,kart);box(1.5,.15,.18,metal,0,.26,-1.05,kart);box(.65,.55,.25,black,0,.75,-.35,kart);box(.6,.15,.6,black,0,.55,0,kart);box(.35,.38,.5,metal,.5,.58,-.5,kart);
const wheels=[];for(const x of [-.75,.75])for(const z of [-.67,.72]){const pivot=new THREE.Group();pivot.position.set(x,.30,z);kart.add(pivot);const tire=mesh(new THREE.CylinderGeometry(.3,.3,.26,20),black,0,0,0,pivot);tire.rotation.z=Math.PI/2;const hub=mesh(new THREE.CylinderGeometry(.14,.14,.275,12),metal,0,0,0,pivot);hub.rotation.z=Math.PI/2;wheels.push({pivot,tire,hub,front:z>0});}
box(.44,.6,.34,mat('#f0c44e'),0,.94,-.16,kart);const helmet=mesh(new THREE.SphereGeometry(.29,24,16),white,0,1.48,-.13,kart);const visor=mesh(new THREE.SphereGeometry(.294,20,12,0,Math.PI),mat('#284856'),0,1.49,-.13,kart);visor.scale.y=.42;
const steering=mesh(new THREE.TorusGeometry(.22,.035,8,20),black,0,.92,.37,kart);steering.rotation.x=-.5;
const keys=new Set();let speed=0,heading=0,steer=0,lap=0,lapTime=0,started=false,checkpoint=0,lastAngle=0,overhead=false,best=null;try{const n=Number(localStorage.getItem('apex-best'));if(n>0)best=n;}catch{}
const format=t=>`${String(Math.floor(t/60)).padStart(2,'0')}:${(t%60).toFixed(2).padStart(5,'0')}`;$('#best').textContent=best?format(best):'—';
function reset(){kart.position.set(RX,0,1.1);heading=0;speed=0;steer=0;lap=0;lapTime=0;checkpoint=0;started=false;lastAngle=0;keys.clear();kart.rotation.y=heading;updateCamera(1);$('#laps').textContent='0';}
$('#reset').onclick=reset;$('#camera').onclick=()=>{overhead=!overhead;$('#camera').textContent=overhead?'切换跟车':'切换俯视';};
addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyW','KeyA','KeyS','KeyD','Space'].includes(e.code)){e.preventDefault();keys.add(e.code);}if(e.code==='KeyR')reset();});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>keys.clear());document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{b.setPointerCapture(e.pointerId);keys.add(b.dataset.key);};b.onpointerup=b.onpointercancel=()=>keys.delete(b.dataset.key);});
let toastTimer;function toast(text){$('.toast').textContent=text;$('.toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('.toast').classList.remove('show'),3000);}
const desired=new THREE.Vector3(),target=new THREE.Vector3();function updateCamera(blend){desired.set(kart.position.x-Math.sin(heading)*(overhead?9:7),overhead?23:4.8,kart.position.z-Math.cos(heading)*(overhead?9:7));camera.position.lerp(desired,blend);target.set(kart.position.x+Math.sin(heading)*2,.7,kart.position.z+Math.cos(heading)*2);camera.lookAt(target);}
reset();let last=performance.now();function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.04);last=now;const gas=keys.has('ArrowUp')||keys.has('KeyW'),brake=keys.has('ArrowDown')||keys.has('KeyS'),handbrake=keys.has('Space');const turn=(keys.has('ArrowLeft')||keys.has('KeyA')?1:0)-(keys.has('ArrowRight')||keys.has('KeyD')?1:0);steer=THREE.MathUtils.damp(steer,turn,9,dt);const next=stepVehicle({x:kart.position.x,z:kart.position.z,speed,heading,steer},{gas,brake,handbrake},dt);({speed,heading,steer}=next);kart.position.x=next.x;kart.position.z=next.z;const onTrack=Math.abs(Math.hypot(next.x/RX,next.z/RZ)-1)<.145;kart.rotation.set(0,heading,-steer*Math.min(Math.abs(speed)/19,1)*.035);wheels.forEach(w=>{w.pivot.rotation.y=w.front?steer*.38:0;w.tire.rotation.x+=speed*dt/.3;});steering.rotation.z=-steer*.5;if(!started&&Math.abs(speed)>.5){started=true;lapTime=0;}if(started)lapTime+=dt;
let angle=Math.atan2(kart.position.z/RZ,kart.position.x/RX);if(angle<0)angle+=Math.PI*2;if(onTrack&&speed>0){if(checkpoint===0&&angle>Math.PI/2&&angle<Math.PI*.8)checkpoint=1;else if(checkpoint===1&&angle>Math.PI&&angle<Math.PI*1.3)checkpoint=2;else if(checkpoint===2&&angle>Math.PI*1.5&&angle<Math.PI*1.8)checkpoint=3;else if(checkpoint===3&&lastAngle>5.5&&angle<.5){lap++;$('#laps').textContent=lap;if(best===null||lapTime<best){best=lapTime;$('#best').textContent=format(best);try{localStorage.setItem('apex-best',String(best));}catch{}toast(`新纪录！${format(lapTime)}`);}else toast(`完成第 ${lap} 圈 · ${format(lapTime)}`);lapTime=0;checkpoint=0;}}lastAngle=angle;$('#time').textContent=format(lapTime);$('#speed').textContent=Math.round(Math.abs(speed)*3.6);updateCamera(1-Math.exp(-dt*5));renderer.render(scene,camera);}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});requestAnimationFrame(frame);
